### PR TITLE
fixed yo shit

### PR DESCRIPTION
**Pull request by munsking**
todo: uncomment stuff, set some kind of warning if the user doesn't exist, remove preventdefaults, set your login info in the config.ini and use the correct commands, you can do it!

### CODE REVIEW

**Comment by thesbros** [comment]
that's the old website. also, you don't need to /reload for adding someone to the whitelist, just /whitelist reload

**Comment by PureTryOut** [comment]
No he needs to reload, as McMyAdmin does a /pex reload, which for some reason breaks PEX (the permission plugin we use). A full /reload fixes this.
And yes old website but will do till we have a proper site.

**Comment by thesbros** [comment]
MCMyAdmin does a pex reload when you do what?

**Comment by munsking** [comment]
then fix it :P also, i'm not gonna create a completely new website, i just need the login to be fixed

**Comment by PureTryOut** [comment]
McMyAdmin does a pex reload once the group configuration is updated (so a user is added or removed from a group, or a permission is added or removed from a group). This should normally work, but for some reason it breaks PEX instead. Using the /pex reload command manually breaks it too, so not a McMyAdmin problem but rather a PEX problem.
Does not matter though, as  a full proper /reload fixes it.

**Comment by thesbros** [comment]
But he's not changing permissions? He's just adding to the whitelist.

**Comment by PureTryOut** [comment]
Yes adding to the McMyAdmin whitelist, which invokes a /pex reload command.

Ooh sorry I now get what you mean ;) He still has the wrong command, he adds someone to the vanilla whitelist, while a user needs to be added to the McMyAdmin one instead. In this case the correct command is "/addmember Registered $mcusername", which then invokes a /pex reload command.

**Comment by thesbros** [comment]
Why does McMyAdmin have it's own whitelist? That seems like the most pointless thing ever...

**Comment by PureTryOut** [comment]
Well it has more options. With McMyAdmin you can choose for:
- Whitelist a single group
- Whitelist anyone that is in a group
- Blacklist everyone but allow them to keep playing till they log out

This does not work with the default whitelist (I guess).

**Pull request merged**
